project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!simulation.qmd"
    - "!cleaning.qmd"
    
website:
  title: "Cit√©-Unis"
  navbar:
    left:
      - href: index.qmd
        text: Report
      - href: tables.qmd
        text: Tables
      - href: codebook.qmd
        text: Codebook

format:
  html:
    toc: true
    toc-depth: 3

execute:
  freeze: auto 
  echo: false
  warning: false
  message: false



