project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!simulation.qmd"
    - "!cleaning.qmd"
    
website:
  title: "Cité-Unis"
  navbar:
    left:
      - text: "Report"
        menu:
          - href: index.qmd
            text: "English"
          - href: index.fr.qmd
            text: "Français"
      - href: tables.qmd
        text: "Tables"
      - href: codebook.qmd
        text: "Codebook"


    right:
      - text: "View Source at {{< fa brands github >}} GitHub"
        href: https://github.com/janpfander/unis-cite

  page-footer: 
    background: light
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Jan Pfänder</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>, 
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    toc: true
    toc-depth: 3

execute:
  freeze: auto 
  echo: false
  warning: false
  message: false

# babelquarto:
#   languagecodes:
#   - name: fr
#     text: "Version in fr"
#   - name: en
#     text: "Version in en"
#   mainlanguage: 'en'
#   languages: ['fr']
# title-fr: title in fr
# description-fr: description in fr
# author-fr: author in fr
# lang: en
